services:
  - type: web
    name: giga-aura
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    domains:
      - gigaaura.com
      - www.gigaaura.com
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BASE_URL
        value: https://www.gigaaura.com
      - key: PORT
        value: 10000 